let customisedGarments = [
	{
    ref: 1,
    garmentTypeRef: 0,
    garmentName: designs[0].name,
    garmentType: designs[0].garment,
    clubIndex: clubs[1].index,
    club: clubs[1].ref,
    sponsorsVersion:"sponsors",
    designRef: 0,
    design: designs[0].designs[0].design,
	path1: designs[0].designs[0].path1,
    path2: designs[0].designs[0].path2,
    sublimatedPattern: "no",
    patternRef: 0,
    pattern:"",
    pathBackground: designs[0].pathBackground[0],
    baseImage: designs[0].baseImage[0],
    colorBackground: "#FFFFFF",
    color1: "#FFFFFF",
    color2: "#FFFFFF",
    colorBackgroundRef: "1",
    color1Ref: "1",
    color2Ref: "1",
    toneBackground: "light",
    tone1: "light",
    tone2: "light",
    clash: "clash",
    rhchest: ["1", "toneBackground"],
    lhchest: ["1", "toneBackground"],
    centrechest: ["1", "toneBackground"],
    mainfront: ["1", "toneBackground"],
    rhcollar: ["1", "toneBackground"],
    lhcollar: ["1", "toneBackground"],
    backtop1: ["1", "toneBackground"],
    backtop2: ["1", "toneBackground"],
    backbottom1: ["1", "toneBackground"],
    backbottom2: ["1", "toneBackground"],
    rhsleeveupper: ["1", "toneBackground"],
    rhsleevelower: ["1", "toneBackground"],
    lhsleeveupper: ["1", "toneBackground"],
    lhsleevelower: ["1", "toneBackground"],
    numberbox: ["1", "toneBackground"],
	},
];
