let customisedGarments = [
    {
    ref: 0,
    garmentType: "prorugbyshirt",
    club: "leedsrhinos",
    sponsorsVersion:"sponsors",
    sponsorsType: designs[0].sponsorsType,
    design: designs[0].design,
    path1: designs[0].path1,
    path2: designs[0].path2,
    pattern:"",
    pathBackground: backgrounds[0].pathBackground,
    baseImage: backgrounds[0].baseImage,
    colorBackground: "#08253d",
    color1: "#ffc629",
    color2: "#505e28",
    toneBackground: "dark",
    tone1: "light",
	},
	{
    ref: 1,
    garmentType: "prorugbyshirt",
    club: "leedsrhinos",
    sponsorsVersion:"sponsors",
    sponsorsType: designs[1].sponsorsType,
    design: designs[1].design,
	path1: designs[1].path1,
    path2: designs[1].path2,
    pattern:"",
    pathBackground: backgrounds[0].pathBackground,
    baseImage: backgrounds[0].baseImage,
    colorBackground: "#223d08",
    color1: "#ca003d",
    color2: "#0d4272",
    toneBackground: "dark",
    tone1: "light",
	},
	{
    ref: 2,
    garmentType: "prorugbyshirt",
    club: "leedsrhinos",
    sponsorsVersion:"logos",
    sponsorsType: designs[2].sponsorsType,
    design: designs[2].design,
    path1: designs[2].path1,
    path2: designs[2].path2,
    pattern:"",
    pathBackground: backgrounds[0].pathBackground,
    baseImage: backgrounds[0].baseImage,
    colorBackground: "#3d082d",
    color1: "#1cd359",
    color2: "#720d3b",
    toneBackground: "dark",
    tone1: "light",
    },
    {
    ref: 3,
    garmentType: "prorugbyshirt",
    club: "leedsrhinos",
    sponsorsVersion:"logos",
    sponsorsType: designs[3].sponsorsType,
    design: designs[3].design,
    path1: designs[3].path1,
    path2: designs[3].path2,
    pattern:"",
    pathBackground: backgrounds[0].pathBackground,
    baseImage: backgrounds[0].baseImage,
    colorBackground: "#223d08",
    color1: "#ca003d",
    color2: "#0d4272",
    toneBackground: "dark",
    tone1: "light",
    },
];
