let customisedGarments = [
	{
    ref: 1,
    garmentTypeRef: 0,
    garmentName: designs[0].name,
    garmentType: designs[0].garment,
    clubIndex: clubs[1].index,
    club: clubs[1].ref,
    sponsorsVersion:"sponsors",
    designRef: 2,
    design: designs[0].designs[2].design,
	path1: designs[0].designs[2].path1,
    path2: designs[0].designs[2].path2,
    patternRef: 0,
    pattern:"",
    pathBackground: designs[0].pathBackground[0],
    baseImage: designs[0].baseImage[0],
    colorBackground: "#FFFFFF",
    color1: "#ed5ddf",
    color2: "#1c355e",
    colorBackgroundRef: 1,
    color1Ref: 4,
    color2Ref: 3,
    toneBackground: "light",
    tone1: "light",
    tone2: "light",
    rhchest: designs[0].designs[2].rhchest,
    lhchest: designs[0].designs[2].lhchest,
    centrechest: designs[0].designs[2].centrechest,
    mainfront: designs[0].designs[2].mainfront,
    rhcollar: designs[0].designs[2].rhcollar,
    lhcollar: designs[0].designs[2].lhcollar,
    backtop1: designs[0].designs[2].backtop1,
    backtop2: designs[0].designs[2].backtop2,
    backbottom1: designs[0].designs[2].backbottom1,
    backbottom2: designs[0].designs[2].backbottom2,
    rhsleeveupper: designs[0].designs[2].rhsleeveupper,
    rhsleevelower: designs[0].designs[2].rhsleevelower,
    lhsleeveupper: designs[0].designs[2].lhsleeveupper,
    lhsleevelower: designs[0].designs[2].lhsleevelower,
    numberbox: designs[0].designs[2].numberbox,
	},
];
