let clubs = [
	{
	"index": 0,
	"name":"Oxen",
	"ref":"noclub",
	"initials": "",

	"logos-rhchest": "45.4mm (W) x 55mm (H)",
	"logos-lhchest": "NO LOGO", 

	"prorugbyshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"prorugbyshirt-lhchest": "NO LOGO",
	"prorugbyshirt-centrechest": "NO LOGO",
	"prorugbyshirt-mainfront": "NO LOGO",
	"prorugbyshirt-rhcollar": "NO LOGO",
	"prorugbyshirt-lhcollar": "NO LOGO", 
	"prorugbyshirt-backtop1": "NO LOGO", 
	"prorugbyshirt-backtop2": "NO LOGO", 
	"prorugbyshirt-backbottom1": "NO LOGO",
	"prorugbyshirt-backbottom2": "NO LOGO", 
	"prorugbyshirt-rhsleeveupper": "NO LOGO",
	"prorugbyshirt-rhsleevelower": "NO LOGO",
	"prorugbyshirt-lhsleeveupper": "NO LOGO",
	"prorugbyshirt-lhsleevelower": "NO LOGO", 
	"prorugbyshirt-numberbox": "NO LOGO", 

	"replicarugbyshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"replicarugbyshirt-lhchest": "NO LOGO",
	"replicarugbyshirt-centrechest": "NO LOGO", 
	"replicarugbyshirt-mainfront": "NO LOGO", 
	"replicarugbyshirt-rhcollar": "NO LOGO",
	"replicarugbyshirt-lhcollar": "NO LOGO",
	"replicarugbyshirt-backtop1": "NO LOGO", 
	"replicarugbyshirt-backtop2": "NO LOGO", 
	"replicarugbyshirt-backbottom1": "NO LOGO", 
	"replicarugbyshirt-backbottom2": "NO LOGO", 
	"replicarugbyshirt-rhsleeveupper": "NO LOGO", 
	"replicarugbyshirt-rhsleevelower": "NO LOGO",
	"replicarugbyshirt-lhsleeveupper": "NO LOGO", 
	"replicarugbyshirt-lhsleevelower": "NO LOGO", 
	"replicarugbyshirt-numberbox": "NO LOGO", 

	"trainingtshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"trainingtshirt-lhchest": "NO LOGO",
	"trainingtshirt-centrechest": "NO LOGO", 
	"trainingtshirt-mainfront": "NO LOGO",
	"trainingtshirt-rhcollar": "NO LOGO", 
	"trainingtshirt-lhcollar": "NO LOGO", 
	"trainingtshirt-backtop1": "NO LOGO", 
	"trainingtshirt-backtop2": "NO LOGO", 
	"trainingtshirt-backbottom1": "NO LOGO", 
	"trainingtshirt-backbottom2": "NO LOGO", 
	"trainingtshirt-rhsleeveupper": "NO LOGO",
	"trainingtshirt-rhsleevelower": "NO LOGO", 
	"trainingtshirt-lhsleeveupper": "NO LOGO", 
	"trainingtshirt-lhsleevelower": "NO LOGO", 
	"trainingtshirt-numberbox": "NO LOGO", 

	"poloshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"poloshirt-lhchest": "NO LOGO",
	"poloshirt-centrechest": "NO LOGO", 
	"poloshirt-mainfront": "NO LOGO", 
	"poloshirt-rhcollar": "NO LOGO", 
	"poloshirt-lhcollar": "NO LOGO", 
	"poloshirt-backtop1": "NO LOGO", 
	"poloshirt-backtop2": "NO LOGO", 
	"poloshirt-backbottom1": "NO LOGO", 
	"poloshirt-backbottom2": "NO LOGO", 
	"poloshirt-rhsleeveupper": "NO LOGO", 
	"poloshirt-rhsleevelower": "NO LOGO", 
	"poloshirt-lhsleeveupper": "NO LOGO",
	"poloshirt-lhsleevelower": "NO LOGO", 
	"poloshirt-numberbox": "NO LOGO", 

	"ohhoodie-rhchest": "45.4mm (W) x 55mm (H)",
	"ohhoodie-lhchest": "NO LOGO",
	"ohhoodie-centrechest": "NO LOGO", 
	"ohhoodie-mainfront": "NO LOGO", 
	"ohhoodie-rhcollar": "NO LOGO", 
	"ohhoodie-lhcollar": "NO LOGO", 
	"ohhoodie-backtop1": "NO LOGO", 
	"ohhoodie-backtop2": "NO LOGO", 
	"ohhoodie-backbottom1": "NO LOGO", 
	"ohhoodie-backbottom2": "NO LOGO", 
	"ohhoodie-rhsleeveupper": "NO LOGO",
	"ohhoodie-rhsleevelower": "NO LOGO", 
	"ohhoodie-lhsleeveupper": "NO LOGO",
	"ohhoodie-lhsleevelower": "NO LOGO", 
	"ohhoodie-numberbox": "NO LOGO", 
	},
	{
	"index": 1,
	"name":"Leeds Rhinos",
	"ref":"leedsrhinos",
	"initials": "LR",

	"logos-rhchest": "45.4mm (W) x 55mm (H)", 
	"logos-lhchest": "101mm (W) x 70mm (H)", 

	"prorugbyshirt-rhchest": "103mm (W) x 42mm (H)",
	"prorugbyshirt-lhchest": "101mm (W) x 70mm (H)", 
	"prorugbyshirt-centrechest": "45.4mm (W) x 55mm (H)", 
	"prorugbyshirt-mainfront": "160mm (W) x 177mm (H)", 
	"prorugbyshirt-rhcollar": "102.9mm (W) x 31.58mm (H)", 
	"prorugbyshirt-lhcollar": "102.9mm (W) x 31.58mm (H)", 
	"prorugbyshirt-backtop1": "NO LOGO", 
	"prorugbyshirt-backtop2": "186.6mm (W) x 85.7mm (H)", 
	"prorugbyshirt-backbottom1": "160mm (W) x 124mm (H)", 
	"prorugbyshirt-backbottom2": "NO LOGO", 
	"prorugbyshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"prorugbyshirt-rhsleevelower": "123mm (W) x 85mm (H)", 
	"prorugbyshirt-lhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"prorugbyshirt-lhsleevelower": "82.7mm (W) x 74mm (H)", 
	"prorugbyshirt-numberbox": "NO LOGO", 

	"replicarugbyshirt-rhchest": "103mm (W) x 42mm (H)",
	"replicarugbyshirt-lhchest": "101mm (W) x 70mm (H)", 
	"replicarugbyshirt-centrechest": "45.4mm (W) x 55mm (H)", 
	"replicarugbyshirt-mainfront": "160mm (W) x 177mm (H)", 
	"replicarugbyshirt-rhcollar": "102.9mm (W) x 31.58mm (H)", 
	"replicarugbyshirt-lhcollar": "102.9mm (W) x 31.58mm (H)", 
	"replicarugbyshirt-backtop1": "NO LOGO", 
	"replicarugbyshirt-backtop2": "186.6mm (W) x 85.7mm (H)", 
	"replicarugbyshirt-backbottom1": "160mm (W) x 124mm (H)", 
	"replicarugbyshirt-backbottom2": "NO LOGO", 
	"replicarugbyshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"replicarugbyshirt-rhsleevelower": "123mm (W) x 85mm (H)", 
	"replicarugbyshirt-lhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"replicarugbyshirt-lhsleevelower": "82.7mm (W) x 74mm (H)", 
	"replicarugbyshirt-numberbox": "NO LOGO", 

	"trainingtshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"trainingtshirt-lhchest": "101mm (W) x 70mm (H)", 
	"trainingtshirt-centrechest": "NO LOGO", 
	"trainingtshirt-mainfront": "160mm (W) x 177mm (H)", 
	"trainingtshirt-rhcollar": "NO LOGO", 
	"trainingtshirt-lhcollar": "NO LOGO", 
	"trainingtshirt-backtop1": "NO LOGO", 
	"trainingtshirt-backtop2": "NO LOGO", 
	"trainingtshirt-backbottom1": "NO LOGO", 
	"trainingtshirt-backbottom2": "NO LOGO", 
	"trainingtshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"trainingtshirt-rhsleevelower": "NO LOGO", 
	"trainingtshirt-lhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"trainingtshirt-lhsleevelower": "NO LOGO", 
	"trainingtshirt-numberbox": "NO LOGO", 

	"poloshirt-rhchest": "72mm (W) x 80mm (H)",
	"poloshirt-lhchest": "101mm (W) x 70mm (H)", 
	"poloshirt-centrechest": "NO LOGO", 
	"poloshirt-mainfront": "NO LOGO", 
	"poloshirt-rhcollar": "NO LOGO", 
	"poloshirt-lhcollar": "80mm (W) x 19.8mm (H)", 
	"poloshirt-backtop1": "NO LOGO", 
	"poloshirt-backtop2": "NO LOGO", 
	"poloshirt-backbottom1": "NO LOGO", 
	"poloshirt-backbottom2": "NO LOGO", 
	"poloshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"poloshirt-rhsleevelower": "NO LOGO", 
	"poloshirt-lhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"poloshirt-lhsleevelower": "NO LOGO", 
	"poloshirt-numberbox": "NO LOGO", 

	"ohhoodie-rhchest": "72mm (W) x 80mm (H)",
	"ohhoodie-lhchest": "101mm (W) x 70mm (H)", 
	"ohhoodie-centrechest": "45.4mm (W) x 55mm (H)", 
	"ohhoodie-mainfront": "NO LOGO", 
	"ohhoodie-rhcollar": "NO LOGO", 
	"ohhoodie-lhcollar": "NO LOGO", 
	"ohhoodie-backtop1": "NO LOGO", 
	"ohhoodie-backtop2": "NO LOGO", 
	"ohhoodie-backbottom1": "NO LOGO", 
	"ohhoodie-backbottom2": "NO LOGO", 
	"ohhoodie-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"ohhoodie-rhsleevelower": "NO LOGO", 
	"ohhoodie-lhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"ohhoodie-lhsleevelower": "NO LOGO", 
	"ohhoodie-numberbox": "NO LOGO", 

	},
	{
	"index": 2,
	"name":"Gloucester",
	"ref":"gloucester",
	"initials": "GR",

	"logos-rhchest": "45.4mm (W) x 55mm (H)",
	"logos-lhchest": "69mm (W) x 80mm (H)", 

	"prorugbyshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"prorugbyshirt-lhchest": "69mm (W) x 80mm (H)",
	"prorugbyshirt-centrechest": "NO LOGO",
	"prorugbyshirt-mainfront": "NO LOGO",
	"prorugbyshirt-rhcollar": "102mm (W) x 57mm (H)",
	"prorugbyshirt-lhcollar": "102mm (W) x 57mm (H)", 
	"prorugbyshirt-backtop1": "SIZE M - 159mm(W) x 58mm(H)<br>SIZE L - 159mm(W) x 58mm(H)<br>SIZE XL - 165mm(W) x 60mm(H)<br>SIZE 2XL - 172mm(W) x 63mm(H)<br>SIZE 3XL - 178mm(W) x 65mm(H)<br>SIZE 4XL - 192mm(W) x 70mm(H)<br>SIZE 5XL - 198mm(W) x 72mm(H)", 
	"prorugbyshirt-backtop2": "SIZE M - 159mm(W) x 58mm(H)<br>SIZE L - 159mm(W) x 58mm(H)<br>SIZE XL - 165mm(W) x 60mm(H)<br>SIZE 2XL - 172mm(W) x 63mm(H)<br>SIZE 3XL - 178mm(W) x 65mm(H)<br>SIZE 4XL - 192mm(W) x 70mm(H)<br>SIZE 5XL - 198mm(W) x 72mm(H)", 
	"prorugbyshirt-backbottom1": "SIZE M - 214mm(W) x 78mm(H)<br>SIZE L - 219mm(W) x 80mm(H)<br>SIZE XL - 230mm(W) x 84mm(H)<br>SIZE 2XL - 247mm(W) x 90mm(H)<br>SIZE 3XL -    260mm(W) x 95mm(H)<br>SIZE 4XL - 260mm(W) x 95mm(H)<br>SIZE 5XL - 260mm(W) x 95mm(H)",
	"prorugbyshirt-backbottom2": "SIZE M - 255mm(W) x 67mm(H)<br>SIZE L - 259mm(W) x 68mm(H)<br>SIZE XL - 270mm(W) x 71mm(H)<br>SIZE 2XL - 286mm(W) x 75mm(H)<br>SIZE 3XL - 297mm(W) x 78mm(H)<br>SIZE 4XL - 297mm(W) x 78mm(H<br>SIZE 5XL - 297mm(W) x 78mm(H)", 
	"prorugbyshirt-rhsleeveupper": "NO LOGO",
	"prorugbyshirt-rhsleevelower": "NO LOGO",
	"prorugbyshirt-lhsleeveupper": "102mm (W) x 120mm (H)",
	"prorugbyshirt-lhsleevelower": "102mm (W) x 16mm (H)", 
	"prorugbyshirt-numberbox": "305mm (W) x 285mm (H)", 

	"replicarugbyshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"replicarugbyshirt-lhchest": "69mm (W) x 80mm (H)",
	"replicarugbyshirt-centrechest": "NO LOGO", 
	"replicarugbyshirt-mainfront": "NO LOGO", 
	"replicarugbyshirt-rhcollar": "102mm (W) x 57mm (H)",
	"replicarugbyshirt-lhcollar": "102mm (W) x 57mm (H)",
	"replicarugbyshirt-backtop1": "SIZE M - 159mm(W) x 58mm(H)<br>SIZE L - 159mm(W) x 58mm(H)<br>SIZE XL - 165mm(W) x 60mm(H)<br>SIZE 2XL - 172mm(W) x 63mm(H)<br>SIZE 3XL - 178mm(W) x 65mm(H)<br>SIZE 4XL - 192mm(W) x 70mm(H)<br>SIZE 5XL - 198mm(W) x 72mm(H)", 
	"replicarugbyshirt-backtop2": "SIZE M - 159mm(W) x 58mm(H)<br>SIZE L - 159mm(W) x 58mm(H)<br>SIZE XL - 165mm(W) x 60mm(H)<br>SIZE 2XL - 172mm(W) x 63mm(H)<br>SIZE 3XL - 178mm(W) x 65mm(H)<br>SIZE 4XL - 192mm(W) x 70mm(H)<br>SIZE 5XL - 198mm(W) x 72mm(H)", 
	"replicarugbyshirt-backbottom1": "SIZE M - 214mm(W) x 78mm(H)<br>SIZE L - 219mm(W) x 80mm(H)<br>SIZE XL - 230mm(W) x 84mm(H)<br>SIZE 2XL - 247mm(W) x 90mm(H)<br>SIZE 3XL -    260mm(W) x 95mm(H)<br>SIZE 4XL - 260mm(W) x 95mm(H)<br>SIZE 5XL - 260mm(W) x 95mm(H)", 
	"replicarugbyshirt-backbottom2": "SIZE M - 255mm(W) x 67mm(H)<br>SIZE L - 259mm(W) x 68mm(H)<br>SIZE XL - 270mm(W) x 71mm(H)<br>SIZE 2XL - 286mm(W) x 75mm(H)<br>SIZE 3XL - 297mm(W) x 78mm(H)<br>SIZE 4XL - 297mm(W) x 78mm(H<br>SIZE 5XL - 297mm(W) x 78mm(H)",  
	"replicarugbyshirt-rhsleeveupper": "NO LOGO", 
	"replicarugbyshirt-rhsleevelower": "NO LOGO",
	"replicarugbyshirt-lhsleeveupper": "NO LOGO", 
	"replicarugbyshirt-lhsleevelower": "NO LOGO", 
	"replicarugbyshirt-numberbox": "NO LOGO", 

	"trainingtshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"trainingtshirt-lhchest": "69mm (W) x 80mm (H)",
	"trainingtshirt-centrechest": "NO LOGO", 
	"trainingtshirt-mainfront": "NO LOGO",
	"trainingtshirt-rhcollar": "NO LOGO", 
	"trainingtshirt-lhcollar": "NO LOGO", 
	"trainingtshirt-backtop1": "NO LOGO", 
	"trainingtshirt-backtop2": "NO LOGO", 
	"trainingtshirt-backbottom1": "NO LOGO", 
	"trainingtshirt-backbottom2": "NO LOGO", 
	"trainingtshirt-rhsleeveupper": "NO LOGO",
	"trainingtshirt-rhsleevelower": "NO LOGO", 
	"trainingtshirt-lhsleeveupper": "NO LOGO", 
	"trainingtshirt-lhsleevelower": "NO LOGO", 
	"trainingtshirt-numberbox": "NO LOGO", 

	"poloshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"poloshirt-lhchest": "69mm (W) x 80mm (H)",
	"poloshirt-centrechest": "NO LOGO", 
	"poloshirt-mainfront": "NO LOGO", 
	"poloshirt-rhcollar": "NO LOGO", 
	"poloshirt-lhcollar": "NO LOGO", 
	"poloshirt-backtop1": "NO LOGO", 
	"poloshirt-backtop2": "NO LOGO", 
	"poloshirt-backbottom1": "NO LOGO", 
	"poloshirt-backbottom2": "NO LOGO", 
	"poloshirt-rhsleeveupper": "NO LOGO", 
	"poloshirt-rhsleevelower": "NO LOGO", 
	"poloshirt-lhsleeveupper": "NO LOGO",
	"poloshirt-lhsleevelower": "NO LOGO", 
	"poloshirt-numberbox": "NO LOGO", 

	"ohhoodie-rhchest": "45.4mm (W) x 55mm (H)",
	"ohhoodie-lhchest": "69mm (W) x 80mm (H)",
	"ohhoodie-centrechest": "NO LOGO", 
	"ohhoodie-mainfront": "NO LOGO", 
	"ohhoodie-rhcollar": "NO LOGO", 
	"ohhoodie-lhcollar": "NO LOGO", 
	"ohhoodie-backtop1": "NO LOGO", 
	"ohhoodie-backtop2": "NO LOGO", 
	"ohhoodie-backbottom1": "NO LOGO", 
	"ohhoodie-backbottom2": "NO LOGO", 
	"ohhoodie-rhsleeveupper": "NO LOGO",
	"ohhoodie-rhsleevelower": "NO LOGO", 
	"ohhoodie-lhsleeveupper": "NO LOGO",
	"ohhoodie-lhsleevelower": "NO LOGO", 
	"ohhoodie-numberbox": "NO LOGO", 
	},
	{
	"index": 3,
	"name":"Castleford Tigers",
	"ref":"castleford",
	"initials": "CT",

	"logos-rhchest": "45.4mm (W) x 55mm (H)",
	"logos-lhchest": "70mm (W) x 70mm (H)", 

	"prorugbyshirt-rhchest": "75mm (W) x 60mm (H)",
	"prorugbyshirt-lhchest": "70mm (W) x 70mm (H)",
	"prorugbyshirt-centrechest": "45.4mm (W) x 55mm (H)",
	"prorugbyshirt-mainfront": "275mm (W) x 109mm (H)",
	"prorugbyshirt-rhcollar": "109mm (W) x 28.9mm (H)",
	"prorugbyshirt-lhcollar": "109mm (W) x 28.9mm (H)", 
	"prorugbyshirt-backtop1": "90.7mm (W) x 35.2mm (H)", 
	"prorugbyshirt-backtop2": "310mm (W) x 63.8mm(H)", 
	"prorugbyshirt-backbottom1": "245mm(W) x 64.1mm(H)",
	"prorugbyshirt-backbottom2": "NO LOGO", 
	"prorugbyshirt-rhsleeveupper": "120mm (W) x 50mm(H)",
	"prorugbyshirt-rhsleevelower": "NO LOGO",
	"prorugbyshirt-lhsleeveupper": "100mm (W) x 60mm(H)",
	"prorugbyshirt-lhsleevelower": "99mm (W) x 60.59mm(H)", 
	"prorugbyshirt-numberbox": "NO LOGO", 

	"replicarugbyshirt-rhchest": "75mm (W) x 60mm (H)",
	"replicarugbyshirt-lhchest": "70mm (W) x 70mm (H)",
	"replicarugbyshirt-centrechest": "45.4mm (W) x 55mm (H)",
	"replicarugbyshirt-mainfront": "275mm (W) x 109mm (H)",
	"replicarugbyshirt-rhcollar": "109mm (W) x 28.9mm (H)",
	"replicarugbyshirt-lhcollar": "109mm (W) x 28.9mm (H)", 
	"replicarugbyshirt-backtop1": "90.7mm (W) x 35.2mm (H)", 
	"replicarugbyshirt-backtop2": "310mm (W) x 63.8mm(H)", 
	"replicarugbyshirt-backbottom1": "245mm(W) x 64.1mm(H)",
	"replicarugbyshirt-backbottom2": "NO LOGO", 
	"replicarugbyshirt-rhsleeveupper": "120mm (W) x 50mm(H)",
	"replicarugbyshirt-rhsleevelower": "NO LOGO",
	"replicarugbyshirt-lhsleeveupper": "100mm (W) x 60mm(H)",
	"replicarugbyshirt-lhsleevelower": "99mm (W) x 60.59mm(H)", 
	"replicarugbyshirt-numberbox": "NO LOGO", 

	"trainingtshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"trainingtshirt-lhchest": "70mm (W) x 70mm (H)",
	"trainingtshirt-centrechest": "NO LOGO", 
	"trainingtshirt-mainfront": "NO LOGO",
	"trainingtshirt-rhcollar": "NO LOGO", 
	"trainingtshirt-lhcollar": "NO LOGO", 
	"trainingtshirt-backtop1": "NO LOGO", 
	"trainingtshirt-backtop2": "NO LOGO", 
	"trainingtshirt-backbottom1": "NO LOGO", 
	"trainingtshirt-backbottom2": "NO LOGO", 
	"trainingtshirt-rhsleeveupper": "NO LOGO",
	"trainingtshirt-rhsleevelower": "NO LOGO", 
	"trainingtshirt-lhsleeveupper": "NO LOGO", 
	"trainingtshirt-lhsleevelower": "NO LOGO", 
	"trainingtshirt-numberbox": "NO LOGO", 

	"poloshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"poloshirt-lhchest": "70mm (W) x 70mm (H)",
	"poloshirt-centrechest": "NO LOGO", 
	"poloshirt-mainfront": "NO LOGO", 
	"poloshirt-rhcollar": "NO LOGO", 
	"poloshirt-lhcollar": "NO LOGO", 
	"poloshirt-backtop1": "NO LOGO", 
	"poloshirt-backtop2": "NO LOGO", 
	"poloshirt-backbottom1": "NO LOGO", 
	"poloshirt-backbottom2": "NO LOGO", 
	"poloshirt-rhsleeveupper": "NO LOGO", 
	"poloshirt-rhsleevelower": "NO LOGO", 
	"poloshirt-lhsleeveupper": "NO LOGO",
	"poloshirt-lhsleevelower": "NO LOGO", 
	"poloshirt-numberbox": "NO LOGO", 

	"ohhoodie-rhchest": "45.4mm (W) x 55mm (H)",
	"ohhoodie-lhchest": "70mm (W) x 70mm (H)",
	"ohhoodie-centrechest": "NO LOGO", 
	"ohhoodie-mainfront": "NO LOGO", 
	"ohhoodie-rhcollar": "NO LOGO", 
	"ohhoodie-lhcollar": "NO LOGO", 
	"ohhoodie-backtop1": "NO LOGO", 
	"ohhoodie-backtop2": "NO LOGO", 
	"ohhoodie-backbottom1": "NO LOGO", 
	"ohhoodie-backbottom2": "NO LOGO", 
	"ohhoodie-rhsleeveupper": "NO LOGO",
	"ohhoodie-rhsleevelower": "NO LOGO", 
	"ohhoodie-lhsleeveupper": "NO LOGO",
	"ohhoodie-lhsleevelower": "NO LOGO", 
	"ohhoodie-numberbox": "NO LOGO", 
	},
	{
	"index": 4,
	"name":"Hull KR",
	"ref":"hullkr",
	"initials": "HKR",

	"logos-rhchest": "45.4mm (W) x 55mm (H)", 
	"logos-lhchest": "56.5mm (W) x 80mm (H)", 

	"prorugbyshirt-rhchest": "103mm (W) x 42mm (H)",
	"prorugbyshirt-lhchest": "56.5mm (W) x 80mm (H)", 
	"prorugbyshirt-centrechest": "45.4mm (W) x 55mm (H)", 
	"prorugbyshirt-mainfront": "NO LOGO", 
	"prorugbyshirt-rhcollar": "NO LOGO", 
	"prorugbyshirt-lhcollar": "NO LOGO", 
	"prorugbyshirt-backtop1": "NO LOGO", 
	"prorugbyshirt-backtop2": "200.8mm (W) x 79mm (H)", 
	"prorugbyshirt-backbottom1": "296.7mm (W) x 67mm (H)", 
	"prorugbyshirt-backbottom2": "NO LOGO", 
	"prorugbyshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"prorugbyshirt-rhsleevelower": "123mm (W) x 85mm (H)", 
	"prorugbyshirt-lhsleeveupper": "131.4mm (W) x 44mm (H)", 
	"prorugbyshirt-lhsleevelower": "96.1mm (W) x 61.5mm (H)", 
	"prorugbyshirt-numberbox": "NO LOGO", 

	"replicarugbyshirt-rhchest": "103mm (W) x 42mm (H)",
	"replicarugbyshirt-lhchest": "56.5mm (W) x 80mm (H)", 
	"replicarugbyshirt-centrechest": "45.4mm (W) x 55mm (H)", 
	"replicarugbyshirt-mainfront": "NO LOGO", 
	"replicarugbyshirt-rhcollar": "NO LOGO", 
	"replicarugbyshirt-lhcollar": "NO LOGO", 
	"replicarugbyshirt-backtop1": "NO LOGO", 
	"replicarugbyshirt-backtop2": "200.8mm (W) x 79mm (H)", 
	"replicarugbyshirt-backbottom1": "296.7mm (W) x 67mm (H)", 
	"replicarugbyshirt-backbottom2": "NO LOGO", 
	"replicarugbyshirt-rhsleeveupper": "157.9mm (W) x 36mm (H)", 
	"replicarugbyshirt-rhsleevelower": "123mm (W) x 85mm (H)", 
	"replicarugbyshirt-lhsleeveupper": "131.4mm (W) x 44mm (H)", 
	"replicarugbyshirt-lhsleevelower": "96.1mm (W) x 61.5mm (H)", 
	"replicarugbyshirt-numberbox": "NO LOGO", 

	"trainingtshirt-rhchest": "45.4mm (W) x 55mm (H)",
	"trainingtshirt-lhchest": "56.5mm (W) x 80mm (H)", 
	"trainingtshirt-centrechest": "NO LOGO", 
	"trainingtshirt-mainfront": "250mm (W) x 125mm (H)", 
	"trainingtshirt-rhcollar": "NO LOGO", 
	"trainingtshirt-lhcollar": "NO LOGO", 
	"trainingtshirt-backtop1": "NO LOGO", 
	"trainingtshirt-backtop2": "NO LOGO", 
	"trainingtshirt-backbottom1": "NO LOGO", 
	"trainingtshirt-backbottom2": "NO LOGO", 
	"trainingtshirt-rhsleeveupper": "NO LOGO", 
	"trainingtshirt-rhsleevelower": "NO LOGO", 
	"trainingtshirt-lhsleeveupper": "NO LOGO", 
	"trainingtshirt-lhsleevelower": "NO LOGO", 
	"trainingtshirt-numberbox": "NO LOGO", 

	"poloshirt-rhchest": "72mm (W) x 80mm (H)",
	"poloshirt-lhchest": "100mm (W) x 50mm (H)", 
	"poloshirt-centrechest": "NO LOGO", 
	"poloshirt-mainfront": "NO LOGO", 
	"poloshirt-rhcollar": "NO LOGO", 
	"poloshirt-lhcollar": "80mm (W) x 19.8mm (H)", 
	"poloshirt-backtop1": "NO LOGO", 
	"poloshirt-backtop2": "NO LOGO", 
	"poloshirt-backbottom1": "NO LOGO", 
	"poloshirt-backbottom2": "NO LOGO", 
	"poloshirt-rhsleeveupper": "NO LOGO", 
	"poloshirt-rhsleevelower": "NO LOGO", 
	"poloshirt-lhsleeveupper": "NO LOGO", 
	"poloshirt-lhsleevelower": "NO LOGO", 
	"poloshirt-numberbox": "NO LOGO", 

	"ohhoodie-rhchest": "72mm (W) x 80mm (H)",
	"ohhoodie-lhchest": "100mm (W) x 50mm (H)", 
	"ohhoodie-centrechest": "45.4mm (W) x 55mm (H)", 
	"ohhoodie-mainfront": "NO LOGO", 
	"ohhoodie-rhcollar": "NO LOGO", 
	"ohhoodie-lhcollar": "NO LOGO", 
	"ohhoodie-backtop1": "NO LOGO", 
	"ohhoodie-backtop2": "NO LOGO", 
	"ohhoodie-backbottom1": "NO LOGO", 
	"ohhoodie-backbottom2": "NO LOGO", 
	"ohhoodie-rhsleeveupper": "NO LOGO", 
	"ohhoodie-rhsleevelower": "NO LOGO", 
	"ohhoodie-lhsleeveupper": "NO LOGO", 
	"ohhoodie-lhsleevelower": "NO LOGO", 
	"ohhoodie-numberbox": "NO LOGO", 

	},
];


