let patterns = [
	{
	"ref":0,
	"name": "None",
	"prorugbyshirt": ["assets/patterns/prorugbyshirt/raglan/pattern0.png", "assets/patterns/prorugbyshirt/setin/pattern0.png"],
	"replicarugbyshirt": ["assets/patterns/replicarugbyshirt/raglan/pattern0.png", "assets/patterns/replicarugbyshirt/setin/pattern0.png"],
	"trainingtshirt": ["assets/patterns/trainingtshirt/raglan/pattern0.png", "assets/patterns/trainingtshirt/setin/pattern0.png"],
	"poloshirt": ["assets/patterns/poloshirt/raglan/pattern0.png", "assets/patterns/poloshirt/setin/pattern0.png"],
	"ohhoodie": ["assets/patterns/ohhoodie/raglan/pattern0.png", "assets/patterns/ohhoodie/setin/pattern0.png"],
	"shade1Ref": "N/A",
	"shade1Hex": "#FFFFFF",
	"shade2Ref": "N/A",
	"shade2Hex": "#FFFFFF",
	},
	{
	"ref":1,
	"name": "Funky Chevrons",
	"prorugbyshirt": ["assets/patterns/prorugbyshirt/raglan/pattern1.png", "assets/patterns/prorugbyshirt/setin/pattern1.png"],
	"replicarugbyshirt": ["assets/patterns/replicarugbyshirt/raglan/pattern1.png", "assets/patterns/replicarugbyshirt/setin/pattern1.png"],
	"trainingtshirt": ["assets/patterns/trainingtshirt/raglan/pattern1.png", "assets/patterns/trainingtshirt/setin/pattern1.png"],
	"poloshirt": ["assets/patterns/poloshirt/raglan/pattern1.png", "assets/patterns/poloshirt/setin/pattern1.png"],
	"ohhoodie": ["assets/patterns/ohhoodie/raglan/pattern1.png", "assets/patterns/ohhoodie/setin/pattern1.png"],
	"colorQuantity": 1,
	"shade1Ref": "Black 20% Opacity",
	"shade1Hex": "#dadada",
	"shade2Ref": "N/A",
	"shade2Hex": "#FFFFFF",
	},
	{
	"ref":2,
	"name": "Morse Code",
	"prorugbyshirt": ["assets/patterns/prorugbyshirt/raglan/pattern2.png", "assets/patterns/prorugbyshirt/setin/pattern2.png"],
	"replicarugbyshirt": ["assets/patterns/replicarugbyshirt/raglan/pattern2.png", "assets/patterns/replicarugbyshirt/setin/pattern2.png"],
	"trainingtshirt": ["assets/patterns/trainingtshirt/raglan/pattern2.png", "assets/patterns/trainingtshirt/setin/pattern2.png"],
	"poloshirt": ["assets/patterns/poloshirt/raglan/pattern2.png", "assets/patterns/poloshirt/setin/pattern2.png"],
	"ohhoodie": ["assets/patterns/ohhoodie/raglan/pattern2.png", "assets/patterns/ohhoodie/setin/pattern2.png"],
	"colorQuantity": 1,
	"shade1Ref": "Black 20%  Opacity",
	"shade1Hex": "#dadada",
	"shade2Ref": "N/A",
	"shade2Hex": "#FFFFFF",
	},
	{
	"ref":3,
	"name": "Sevens",
	"prorugbyshirt": ["assets/patterns/prorugbyshirt/raglan/pattern3.png", "assets/patterns/prorugbyshirt/setin/pattern3.png"],
	"replicarugbyshirt": ["assets/patterns/replicarugbyshirt/raglan/pattern3.png", "assets/patterns/replicarugbyshirt/setin/pattern3.png"],
	"trainingtshirt": ["assets/patterns/trainingtshirt/raglan/pattern3.png", "assets/patterns/trainingtshirt/setin/pattern3.png"],
	"poloshirt": ["assets/patterns/poloshirt/raglan/pattern3.png", "assets/patterns/poloshirt/setin/pattern3.png"],
	"ohhoodie": ["assets/patterns/ohhoodie/raglan/pattern3.png", "assets/patterns/ohhoodie/setin/pattern3.png"],
	"colorQuantity": 2,
	"shade1Ref": "Black 20%  Opacity",
	"shade1Hex": "#dadada",
	"shade2Ref": "Black 10% Opacity",
	"shade2Hex": "#ededed",
	},
];
